name: Collaborative Workflow

on:
  push:
    branches:
      - main

jobs:
  update_html_and_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update for User 1
        if: ${{ github.actor == 'AshReign' }}
        run: echo "<p>Updated by AshReign</p>" >> index.html
