name: Collaborative Workflow

on:
  push:
    branches:
      - main

jobs:
  update_html_and_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update for User 1
        if: ${{ github.actor == 'AshReign' }}
        run: echo "<p>Updated by AshReign</p>" >> index.html
      - name: Append to README.md
        run: echo "Update to index.html by ${{ github.actor }} on $(date)" >> README.md
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Workflow: Updated HTML and README for ${{ github.actor }}" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
